"""Initial migration

Revision ID: c82e36dbe23f
Revises: 
Create Date: 2023-10-15 16:43:32.548355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import adapters


# revision identifiers, used by Alembic.
revision: str = 'c82e36dbe23f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('house',
    sa.Column('id', adapters.orm.GUID(), nullable=False),
    sa.Column('coexistence', sa.Float(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cat',
    sa.Column('id', adapters.orm.GUID(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('nature', adapters.orm.Nature(), nullable=False),
    sa.Column('house_id', adapters.orm.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cat')
    op.drop_table('house')
    # ### end Alembic commands ###
